In [22]:
import numpy as np # linear algebra
import pandas as pd
import re # text processing
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_validate,cross_val_score
from sklearn.preprocessing import LabelEncoder

In [33]:
train_data=pd.read_csv("/home/ubuntu/ML/titanic/train.csv")
test_data=pd.read_csv("/home/ubuntu/ML/titanic/test.csv")

In [34]:
#train_data.shape#891,12

test_data.shape#418,11

(418, 11)

In [35]:
train_data.head()

X_train = train_data.drop(['Survived'],axis=1)
y_train = train_data['Survived']

X_test=test_data

In [36]:
sex_encoder = LabelEncoder()
X_train['Sex'] = sex_encoder.fit_transform(X_train['Sex'])
X_test['Sex'] = sex_encoder.fit_transform(X_test['Sex'])

In [16]:
X_train['Has_Cabin']=X_train['Cabin'].apply(lambda x: 0 if type(x) == float else 1)
#X_train['Sex']=X_train['Sex'].map({"male":1,"female":0})
X_train['Embarked']=X_train['Embarked'].map({"S":2,"C":1,"Q":3}).fillna(0).astype(int)


X_test['Has_Cabin']=X_test['Cabin'].apply(lambda x: 0 if type(x) == float else 1)
#X_test['Sex']=X_test['Sex'].map({"male":1,"female":0})
X_test['Embarked']=X_test['Embarked'].map({"S":2,"C":1,"Q":3}).fillna(0).astype(int)

KeyError: 'Cabin'

In [15]:
#X_train['Age'].isnull().sum()
X_train['Age']=X_train['Age'].fillna(X_train['Age'].mean()).astype(int)
#X_train
#X_train['Age'].mean()

X_test['Age']=X_test['Age'].fillna(X_test['Age'].mean()).astype(int)
#X_test

In [11]:
X_train=X_train.drop(['PassengerId','Name','Ticket','Fare','Cabin'],axis=1)
X_test=X_test.drop(['PassengerId','Name','Ticket','Fare','Cabin'],axis=1)

In [12]:
X_train

     Pclass  Sex  Age  SibSp  Parch  Embarked  Has_Cabin
0         3    1   22      1      0         2          0
1         1    0   38      1      0         1          1
2         3    0   26      0      0         2          0
3         1    0   35      1      0         2          1
4         3    1   35      0      0         2          0
5         3    1   29      0      0         3          0
6         1    1   54      0      0         2          1
7         3    1    2      3      1         2          0
8         3    0   27      0      2         2          0
9         2    0   14      1      0         1          0
10        3    0    4      1      1         2          1
11        1    0   58      0      0         2          1
12        3    1   20      0      0         2          0
13        3    1   39      1      5         2          0
14        3    0   14      0      0         2          0
15        2    0   55      0      0         2          0
16        3    1    2      4      1         3          0
17        2    1   29      0      0         2          0
18        3    0   31      1      0         2          0
19        3    0   29      0      0         1          0
20        2    1   35      0      0         2          0
21        2    1   34      0      0         2          1
22        3    0   15      0      0         3          0
23        1    1   28      0      0         2          1
24        3    0    8      3      1         2          0
25        3    0   38      1      5         2          0
26        3    1   29      0      0         1          0
27        1    1   19      3      2         2          1
28        3    0   29      0      0         3          0
29        3    1   29      0      0         2          0
..      ...  ...  ...    ...    ...       ...        ...
861       2    1   21      1      0         2          0
862       1    0   48      0      0         2          1
863       3    0   29      8      2         2          0
864       2    1   24      0      0         2          0
865       2    0   42      0      0         2          0
866       2    0   27      1      0         1          0
867       1    1   31      0      0         2          1
868       3    1   29      0      0         2          0
869       3    1    4      1      1         2          0
870       3    1   26      0      0         2          0
871       1    0   47      1      1         2          1
872       1    1   33      0      0         2          1
873       3    1   47      0      0         2          0
874       2    0   28      1      0         1          0
875       3    0   15      0      0         1          0
876       3    1   20      0      0         2          0
877       3    1   19      0      0         2          0
878       3    1   29      0      0         2          0
879       1    0   56      0      1         1          1
880       2    0   25      0      1         2          0
881       3    1   33      0      0         2          0
882       3    0   22      0      0         2          0
883       2    1   28      0      0         2          0
884       3    1   25      0      0         2          0
885       3    0   39      0      5         3          0
886       2    1   27      0      0         2          0
887       1    0   19      0      0         2          1
888       3    0   29      1      2         2          0
889       1    1   26      0      0         1          1
890       3    1   32      0      0         3          0

[891 rows x 7 columns]

In [86]:
X_test

     Pclass  Sex  Age  SibSp  Parch  Embarked  Has_Cabin
0         3    1   34      0      0         3          0
1         3    0   47      1      0         2          0
2         2    1   62      0      0         3          0
3         3    1   27      0      0         2          0
4         3    0   22      1      1         2          0
5         3    1   14      0      0         2          0
6         3    0   30      0      0         3          0
7         2    1   26      1      1         2          0
8         3    0   18      0      0         1          0
9         3    1   21      2      0         2          0
10        3    1   30      0      0         2          0
11        1    1   46      0      0         2          0
12        1    0   23      1      0         2          1
13        2    1   63      1      0         2          0
14        1    0   47      1      0         2          1
15        2    0   24      1      0         1          0
16        2    1   35      0      0         3          0
17        3    1   21      0      0         1          0
18        3    0   27      1      0         2          0
19        3    0   45      0      0         1          0
20        1    1   55      1      0         1          0
21        3    1    9      0      1         2          0
22        1    0   30      0      0         2          0
23        1    1   21      0      1         1          0
24        1    0   48      1      3         1          1
25        3    1   50      1      0         2          0
26        1    0   22      0      1         1          1
27        3    1   22      0      0         1          0
28        1    1   41      0      0         2          1
29        3    1   30      2      0         1          0
..      ...  ...  ...    ...    ...       ...        ...
388       3    1   21      0      0         3          0
389       3    1    6      3      1         2          0
390       1    1   23      0      0         2          1
391       1    0   51      0      1         2          1
392       3    1   13      0      2         2          0
393       2    1   47      0      0         2          0
394       3    1   29      3      1         2          0
395       1    0   18      1      0         2          1
396       3    1   24      0      0         3          0
397       1    0   48      1      1         1          1
398       3    1   22      0      0         2          0
399       3    1   31      0      0         3          0
400       1    0   30      0      0         2          1
401       2    1   38      1      0         2          0
402       1    0   22      0      1         1          0
403       1    1   17      0      0         2          0
404       1    1   43      1      0         1          1
405       2    1   20      0      0         1          1
406       2    1   23      1      0         2          0
407       1    1   50      1      1         1          1
408       3    0   30      0      0         3          0
409       3    0    3      1      1         2          0
410       3    0   30      0      0         3          0
411       1    0   37      1      0         3          1
412       3    0   28      0      0         2          0
413       3    1   30      0      0         2          0
414       1    0   39      0      0         1          1
415       3    1   38      0      0         2          0
416       3    1   30      0      0         2          0
417       3    1   30      1      1         1          0

[418 rows x 7 columns]

In [87]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
y_test=lr.predict(X_test)


#logreg_acc_score = round(logreg.score(X_train, y_train) * 100, 2)

In [90]:
y_test

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0])

In [107]:
cv_results = cross_val_score(lr, X_train, y_train,cv=10).mean()

In [108]:
cv_results

0.79457638179548284